config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :trips
  get "/destinations", to: "trips#destinations"
  get "/categories", to: "trips#categories"
  get "/about", to: "trips#about"
  get "/aboutstory", to: "trips#aboutstory"
  get "/aboutpast", to: "trips#aboutpast"
  get "/aboutoffer", to: "trips#aboutoffer"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user

  has_many_attached :photos

  CATEGORIES = ["Ayurveda", "Hiking", "Yoga", "Meditation", "Nutrition", "Medical Spa", "Spa", "Fitness", "General Wellness"]
end

app/models/trip_category.rb
class TripCategory < ApplicationRecord
  belongs_to :trip
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[show edit destroy]

  def index
    @fallback_image = 'https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg'

    if params[:query].present?
      @trips = Trip.where("name ILIKE :query OR address ILIKE :query OR description ILIKE :query", query: "%#{params[:query]}%")
    else
      @trips = Trip.all
    end
  end

  def show
    # @trip= Trip.find(params[:id])
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    # Removes the empty item ("") being sent by simple form
    @trip.categories = @trip.categories.select(&:present?)

    if @trip.save
      redirect_to trip_path(@trip)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # @trip = Trip.find(params[:id])
  end

  def update
    # @trip = Trip.find(params[:id])

    @trip = Trip.update(trip_params)
    redirect_to trip_path(@trip)
  end

  def destroy
    # @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to trip_path, status: :see_other
  end

  def select
    @user_trips = Trip.where(user: current_user)
  end

  def destinations
    @trips = Trip.all
  end

  def categories
    @trips = Trip.all
  end

  def list
    @trips = Trip.all
  end

  private

  def set_trip
    @trip = Trip.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(:name,
                                 :address,
                                 :start_date, :end_date,
                                 :deposit_pricing,
                                 :double_pricing,
                                 :single_pricing,
                                 :max_participants,
                                 :description,
                                 categories: [],
                                 photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bewelltrips</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://kit.fontawesome.com/bed4839928.js" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <main>
      <%= yield %>
    </main>
    <%= render "shared/footer" %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/home.html.erb
  <div class="d-flex flex-container justify-content-evenly flex-column align-items-center vw-100 vh-100">

   <div class="banner d-flex flex-column">
      <div class="banner-content">

          <h1> Wellness Retreats </h1>
          <h2> Book or Plan</h2>

           <div>  <p class="typewriter" > We make it easier for you!</p>   </div>

      </div>

  </div>


    <div class="search_bar d-flex search-location">
      <%= form_with url: trips_path, method: :get, class: "d-flex flex-grow-1 mx-4" do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control flex-grow-1 me-2",
        placeholder: "Where would you like to go?"%>
        <%= submit_tag "Go", class: "btn-simple"%>
      <% end %>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer footer-links position-fixed bottom-0 bg-white w-100">

    <%= link_to root_path do %>
      <i class="fa-solid fa-house fa-1xl"></i>
    <% end %>
    <%= link_to destinations_path do %>
      <%# <i class="fa-solid fa-spa fa-1xl"></i> %>
      <i class="fa-solid fa-magnifying-glass fa-1xl"></i>
    <% end %>

    <%= link_to categories_path do %>
      <i class="fa-solid fa-spa fa-1xl"></i>
    <% end %>

    <%= link_to root_path do %>
      <i class="fa-regular fa-comment-dots fa-1xl"></i>
    <% end %>


</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon position-fixed bg-white top-0 w-100">
  <div class="container-fluid position-relative">
    <%= link_to root_path, class: "navbar-brand position-absolute top-0" do %>
      <%= image_tag "bewelltripslogo.svg" %>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

      </ul>
    </div>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">

            <%= link_to "About us", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Destinations",destinations_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
           <%= link_to "Retreat Types", categories_path, class: "nav-link" %>
           </li>
            <li class="nav-item">
            <%= link_to "Planner Dashboard",  new_trip_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
           <%= link_to "Contact Us", "#", class: "nav-link" %>
          </li>

             <li class="nav-item dropdown">

            <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar3.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <div class="container-fluid">
  <div>
      <%= link_to image_tag("bewelltrips.png"), root_path , class: "navbar-brand"%>
  </div>
<%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
</button> %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <li class="nav-item">
          <%= link_to "Our Story", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Gallery", "#", class: "nav-link" %>
        </li>
          <li class="nav-item active">
          <%= link_to "Destinations", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", "#", class: "nav-link" %>
        </li>

      </ul>

    </div>


    <div>

      <button>
        <%= link_to "Contact Us", "#", class: "nav-link" %>
      </button>
  </div>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
       <% if user_signed_in? %>

        <li>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
        </li>

      </div>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
       <%# <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <%# </li> %>

      </ul>
    </div>
  </div>
</div>

app/views/trips/about.html.erb
<div class= "container">
<div class="form-retreat-list">
  <h2>How it All Started...</h2>
</div>

<ul class="nav nav-tabs m-5">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="#" style="color:grey;">Our Story</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href= "#" style="color:grey">Past Events</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#" style="color:grey;">What We Do</a>
  </li>

</ul>






</div>

app/views/trips/aboutoffer.html.erb
what we offer

app/views/trips/aboutpast.html.erb
past events

app/views/trips/aboutstory.html.erb
our Story

app/views/trips/categories.html.erb
<div class= "container">
<div class="form-retreat-list">
  <h2> What type of Wellness Activities are you Interested in ?</h2>
</div>

<div class="form-retreat-categories justify-content-center  d-flex flex-space-around" >


   <%= link_to categories_path, class: "btn-categories d-flex flex-column" do %>
      <span>Yoga</span>
      <div class="d-flex align-items-center justify-content-center flex-grow-1">
         <i class="fa-solid fa-om fa-2xl"></i>
      </div>
    <% end %>
    <%= link_to categories_path, class: "btn-categories d-flex flex-column" do %>
      <span>Hiking</span>
      <div class="d-flex align-items-center justify-content-center flex-grow-1">
        <i class= "fa-solid fa-person-hiking fa-2xl"></i>
      </div>
    <% end %>
    <%= link_to categories_path, class: "btn-categories d-flex flex-column" do %>
      <span>Spa</span>
      <div class="d-flex align-items-center justify-content-center flex-grow-1">
        <i class="fa-solid fa-spa fa-2xl"></i>
      </div>
    <% end %>
     <%= link_to categories_path, class: "btn-categories d-flex flex-column" do %>
      <span>Fitness</span>
      <div class="d-flex align-items-center justify-content-center flex-grow-1">
        <i class="fa-solid fa-heart-pulse fa-2xl"></i>
      </div>
    <% end %>

 </div>
<div class="cards-container my-4">
  <div class="flex-item justify-content-right">
        <div class= "search_bar d-flex flex-column">
            <%= form_with url: trips_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search Retreat Category"%>
            <%= submit_tag "Go", class: "btn-search"%>
            <% end %>
        </div>
  </div>
 </div>
<div class="cards-container">


  <div class="row justify-content-center">
  <div class="col-11 col-md-8 col-lg-6">
  <div class="trip-cards my-2">
  <% @trips.each do |trip| %>
    <%= link_to trip_path(trip) do %>
      <div class="card-trip">
        <div class="card-trip-image" style="background-image: url('<%= trip.photos.attached? ? cl_image_path(trip.photos.first.key) : @fallback_image %>')">
        </div>
        <div class="card-trip-infos">
          <div>
            <h2><%= trip.name %></h2>
            <h4 class="card-trip-pricing">
              <%="$#{trip.double_pricing}"%>-<%="$#{trip.single_pricing}"%>
            </h4>
            <p>Overview:<%= trip.description %></p>
            <%= trip.categories.join(" | ")%>
          </div>

        </div>
      </div>
    <% end %>
  <% end %>
  </div>
</div>
  </div>
  </div>

  </div>

app/views/trips/index.html.erb
<div class="form-retreat-list">
  <h2>Retreats</h2>
</div>

<div class="cards-container my-4">
  <div class="flex-item justify-content-right">
        <div class= "search_bar d-flex flex-column">
            <%= form_with url: trips_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Where would you like to go?"%>
            <%= submit_tag "Go", class: "btn-search"%>
            <% end %>
        </div>
  </div>
 </div>
<div class="cards-container">


  <div class="row justify-content-center">
  <div class="col-11 col-md-8 col-lg-6">
  <div class="trip-cards my-2">
  <% @trips.each do |trip| %>
    <%= link_to trip_path(trip) do %>
      <div class="card-trip">
        <div class="card-trip-image" style="background-image: url('<%= trip.photos.attached? ? cl_image_path(trip.photos.first.key) : @fallback_image %>')">
        </div>
        <div class="card-trip-infos">
          <div>
            <h2><%= trip.name %></h2>
            <h4 class="card-trip-pricing">
              <%="$#{trip.double_pricing}"%>-<%="$#{trip.single_pricing}"%>
            </h4>
            <p>Overview:<%= trip.description %></p>
            <%= trip.categories.join(" | ")%>
          </div>

        </div>
      </div>
    <% end %>
  <% end %>
  </div>
</div>
  </div>
  </div>

app/views/trips/index3.html.erb
<div class="form-retreat-list">
  <h2>Upcoming Retreats</h2>
</div>


<div class="cards-container">

  <div class="trip-cards">

  <% @trips.each do |t| %>
    <%= link_to trip_path(t) do %>
     <div class="card-trip">
      <% if t.photos.attached? %>
        <%= cl_image_tag t.photos.first.key %>
      <% else %>
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg">
      <% end %>
        <div class="card-trip">
          <div>
            <h2><%= t.name %></h2>
            <p>Overview:<%= t.description %></p>
            <p>Start Date<%= t.start_date %></p>
            <p>End Date<%= t.end_date %></p>
          </div>
          <h2 class="card-trip-pricing"><%= "$#{t.double_pricing}"%></h2>
        </div>
    </div>
  <% end %>
<% end %>

  </div>
</div>

app/views/trips/index4.html.erb
<%# <div class="form-retreat-list">
  <h2>Upcoming Retreats</h2>
</div> %>

<div container>
  <div class="row">
    <div class="col-12 col-md-6 col-lg-4">
      <% @trips.each do |t| %>
      <%= link_to trip_path(t) do %>
        <div class="card">
          <% if t.photos.attached? %>
            <%= cl_image_tag t.photos.first.key %>
          <% else %>
            <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
          <% end %>
           <div class="card-body">
                <div class="card-title">
                  <h2><%= t.name %></h2>
                </div>
                <div class="card-text">
                  <h2><%= t.description %></h2>
                </div>
          </div>
        </div>
     </div>
  </div>
</div>
<%# <div class="cards row"> %>
  <%# <div class="col-12 col-md-6 col-lg-4"> %>
  <% @trips.each do |t| %>
    <%= link_to trip_path(t) do %>
      <%# <div class="card-trip"> %>
        <% if t.photos.attached? %>
          <%= cl_image_tag t.photos.first.key %>
        <% else %>
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= t.name %></h2>
            <h4 class="card-trip-pricing">
              <%="$#{t.double_pricing}"%>-<%="$#{t.double_pricing}"%>
            </h4>
            <p>Overview:<%= t.description %></p>
            <%= t.categories.join(" | ")%>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  </div>

app/views/trips/list.html.erb
<% @trips.each do |t|%>
  <h5> <%= t.name %>  </h5>
<% end %>

app/views/trips/new.html.erb
<div class="form-retreat-manager">
  <h2>Plan Your Retreat and View Reports!</h2>
</div>

<div class="form-retreat-manager justify-content-center  d-flex flex-space-around" >

   <%= link_to new_trip_path, class: "btn-dashboard d-flex flex-column" do %>
      <span>All Trips</span>
      <div class="d-flex align-items-center justify-content-center flex-grow-1">
         <i class="fa-solid fa-list-check fa-2xl"></i>
      </div>
    <% end %>
    <%= link_to new_trip_path, class: "btn-dashboard d-flex flex-column" do %>
      <span>Add Trip</span>
      <div class="d-flex align-items-center justify-content-center flex-grow-1">
        <i class="fa-solid fa-circle-plus fa-2xl"></i>
      </div>
    <% end %>
    <%= link_to new_trip_path, class: "btn-dashboard d-flex flex-column" do %>
      <span>Edit Trip</span>
      <div class="d-flex align-items-center justify-content-center flex-grow-1">
        <i class="fa-solid fa-pen fa-2xl"></i>
      </div>
    <% end %>
     <%= link_to new_trip_path, class: "btn-dashboard d-flex flex-column" do %>
      <span>Reports</span>
      <div class="d-flex align-items-center justify-content-center flex-grow-1">
        <i class="fa-solid fa-chart-line fa-2xl"></i>
      </div>
    <% end %>

 </div>

  <div class="row justify-content-center">
    <div class="col-12 col-sm-4">

  <div class="form-retreat">

  <h2>Add a New Retreat </h2>
      <%= simple_form_for @trip do |f| %>
        <%= f.input :name, label:"Retreat Name:"%>
        <%= f.input :address, label:"Retreat Location:" %>
        <%= f.input :start_date,label:"Retreat Start Date:", as: :date, html5: true %>
        <%= f.input :end_date,label:"Retreat End Date:", as: :date, html5: true %>
        <%= f.input :deposit_pricing, label:"Deposit Amount:" %>
        <%= f.input :double_pricing, label:"Double Accommodations Pricing:" %>
        <%= f.input :single_pricing, label:"Single Accommodations Pricing:" %>
        <%= f.input :max_participants, label:"Maximum Number of Participants:" %>
        <%= f.input :categories, label: "Activity Types:", collection: Trip::CATEGORIES, input_html: { multiple: true }, as: :check_boxes %>
        <%= f.input :description, label:"Retreat Description:" %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit "Create Retreat", class: "btn-create" %>
     <% end %>
 </div>
    </div>
  </div>
</div>

app/views/trips/setaside.html.erb
<div class="form_book">
  <p><%= @trip.description %></p>
</div>
<div class="form_book">
<h4> € <strong><%= @trip.price%></strong>/day</h4>
</div>
<div class="form_book">
  <%# Form to create a booking - uncomment to unleash! %>
  <%= render "bookings/form", trip:@eventspace, booking:@booking %>
</div>

</div>

app/views/trips/show1.html.erb
<div class="container">

<div class="form_retreat">
  <h1>
   <i class="bi bi-chevron-compact-left"></i>
    <%= @trip.name %>
  </h1>
  <p><%= @trip.address%></p>
</div>
<div class="form_retreat">
  <div class="d-flex img-grid-wrapper">
    <div class="trip-img-grid img-grid-big w-50 me-2" style="background-image: url(<%= cl_image_path @trip.photos.first.key %>)"></div>
    <div class="w-50 img-grid-small">
      <% @trip.photos.drop(1).each do |photo| %>
        <div class="trip-img-grid w-100 h-100" style="background-image: url(<%= cl_image_path photo.key %>)"></div>
      <% end %>
    </div>
  </div>
</div>


<div class="form_retreat">
  <p><%= @trip.description %></p>
</div>
<div class="form_retreat">
<h4> € <strong><%= @trip.deposit_pricing%></strong></h4>
</div>


</div>

app/views/trips/showold.html.erb
<div class="container">

<div class="form_retreat">
  <h1>
   <i class="bi bi-chevron-compact-left"></i>
    <%= @trip.name %>
  </h1>
  <p><%= @trip.address%></p>
</div>
<div class="form_retreat">
  <div class="d-flex img-grid-wrapper">
    <div class="trip-img-grid img-grid-big w-50 me-2" style="background-image: url(<%= cl_image_path @trip.photos.first.key %>)"></div>
    <div class="w-50 img-grid-small">
      <% @trip.photos.drop(1).each do |photo| %>
        <div class="trip-img-grid w-100 h-100" style="background-image: url(<%= cl_image_path photo.key %>)"></div>
      <% end %>
    </div>
  </div>
</div>


<div class="form_retreat">
  <p><%= @trip.description %></p>
</div>
<div class="form_retreat">
<h4> € <strong><%= @trip.deposit_pricing%></strong></h4>
</div>


</div>

app/views/trips/showtest.html.erb
<div class="image-grid-container">

  <div class="row justify-content-center">

    <% @trip.photos.each do |photo| %>
        <%= cl_image_tag photo.key,  class:"image-grid-item"%>
    <% end %>
  </div>
</div>

<div class="retreat-info-container justify-content-left">
  <h2><%= @trip.name %></h2>
</div>

<div class="retreat-info-container">
 <p> <i class="fa-solid fa-location-dot"></i> <%= @trip.address %></p>
</div>

<div class="retreat-info-container justify-content-right">
 <h5><%= @trip.categories.join(" | ")%></h5>
</div>


<div class="retreat-info-container">
 <p> <i class="fa-solid fa-calendar-days"></i>
 <strong>From: </strong> <%= @trip.start_date%> <strong>To: </strong><%= @trip.end_date%> </p>
</div>

<div class="retreat-info-container">
 <p><strong>Overview: </strong><br><%= @trip.description %></p>
</div>